name: Bump spike-spky formula

on:
  release:
    types: [published]

jobs:
  bump-formula:
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        run: |
          brew update

      - name: Bump formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          TAG="${{ github.event.release.tag_name }}"
          URL="https://github.com/YOURUSER/spike-spky/archive/refs/tags/${TAG}.tar.gz"
          brew tap YOURUSER/tap https://github.com/YOURUSER/homebrew-tap
          brew bump-formula-pr --force --no-browse --url="$URL" YOURUSER/tap/spike-spky